/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Language {
  JS = 0,
  JSX = 1,
  TS = 2,
  TSX = 3,
  JSON = 4,
  YAML = 5,
  CSS = 6,
  HTML = 7,
  Regex = 8,
  JsDoc = 9,
  C = 10,
  Bash = 11,
  Rust = 12
}
export declare function highlight(code: string, language: Language): string
export interface HastProperties {
  className: string
}
export interface HastNode {
  type: string
  tagName: string
  properties: HastProperties
  children: Array<HastNode | HastTextNode>
}
export interface HastTextNode {
  type: string
  value: string
}
export declare function highlightHast(code: string, language: Language): HastNode
