use napi_derive::napi;

#[napi]
pub const HIGHLIGHT_NAMES: &[&str] = &[
    "attribute",
    "boolean",
    "character.special",
    "comment",
    "constant",
    "constant.builtin",
    "constant.character",
    "constructor",
    "embedded",
    "escape",
    "function",
    "function.builtin",
    "function.method",
    "keyword",
    "label",
    "number",
    "operator",
    "property",
    "punctuation.bracket",
    "punctuation.delimiter",
    "punctuation.special",
    "string",
    "string.special",
    "string.special.key",
    "tag",
    "tag.error",
    "type",
    "type.builtin",
    "variable",
    "variable.builtin",
    "variable.parameter",
];

pub const CLASS_NAMES: &[&str] = &[
    "attribute",
    "boolean",
    "character special",
    "comment",
    "constant",
    "constant builtin",
    "constant character",
    "constructor",
    "embedded",
    "escape",
    "function",
    "function builtin",
    "function method",
    "keyword",
    "label",
    "number",
    "operator",
    "property",
    "punctuation bracket",
    "punctuation delimiter",
    "punctuation special",
    "string",
    "string special",
    "string special key",
    "tag",
    "tag error",
    "type",
    "type builtin",
    "variable",
    "variable builtin",
    "variable parameter",
];
