pub const HIGHLIGHT_NAMES: &[&str] = &[
    "attribute",
    "character.special",
    "comment",
    "constant",
    "constant.builtin",
    "constant.character",
    "constructor",
    "embedded",
    "escape",
    "function",
    "function.builtin",
    "function.method",
    "keyword",
    "number",
    "operator",
    "property",
    "punctuation.bracket",
    "punctuation.delimiter",
    "punctuation.special",
    "string",
    "string.special",
    "tag",
    "type",
    "type.builtin",
    "variable",
    "variable.builtin",
    "variable.parameter",
];

pub const HTML_ATTRS: &[&str] = &[
    "class=\"attribute\"",
    "class=\"character special\"",
    "class=\"comment\"",
    "class=\"constant\"",
    "class=\"constant builtin\"",
    "class=\"constant character\"",
    "class=\"constructor\"",
    "class=\"embedded\"",
    "class=\"escape\"",
    "class=\"function\"",
    "class=\"function builtin\"",
    "class=\"function method\"",
    "class=\"keyword\"",
    "class=\"number\"",
    "class=\"operator\"",
    "class=\"property\"",
    "class=\"punctuation bracket\"",
    "class=\"punctuation delimiter\"",
    "class=\"punctuation special\"",
    "class=\"string\"",
    "class=\"string special\"",
    "class=\"tag\"",
    "class=\"type\"",
    "class=\"type builtin\"",
    "class=\"variable\"",
    "class=\"variable builtin\"",
    "class=\"variable parameter\"",
];

pub const CLASS_NAMES: &[&str] = &[
    "attribute",
    "character special",
    "comment",
    "constant",
    "constant builtin",
    "constant character",
    "constructor",
    "embedded",
    "escape",
    "function",
    "function builtin",
    "function method",
    "keyword",
    "number",
    "operator",
    "property",
    "punctuation bracket",
    "punctuation delimiter",
    "punctuation special",
    "string",
    "string special",
    "tag",
    "type",
    "type builtin",
    "variable",
    "variable builtin",
    "variable parameter",
];
