pub const HIGHLIGHT_NAMES: &[&str] = &[
    "attribute",
    "boolean",
    "character.special",
    "comment",
    "comment.documentation",
    "constant",
    "constant.builtin",
    "constant.character",
    "constructor",
    "delimiter",
    "embedded",
    "escape",
    "function",
    "function.builtin",
    "function.macro",
    "function.method",
    "function.special",
    "keyword",
    "label",
    "number",
    "operator",
    "property",
    "punctuation.bracket",
    "punctuation.delimiter",
    "punctuation.special",
    "string",
    "string.special",
    "string.special.key",
    "tag",
    "tag.error",
    "type",
    "type.builtin",
    "variable",
    "variable.builtin",
    "variable.parameter",
];

pub const HTML_ATTRS: &[&str] = &[
    "class=\"attribute\"",
    "class=\"boolean\"",
    "class=\"character special\"",
    "class=\"comment\"",
    "class=\"comment documentation\"",
    "class=\"constant\"",
    "class=\"constant builtin\"",
    "class=\"constant character\"",
    "class=\"constructor\"",
    "class=\"delimiter\"",
    "class=\"embedded\"",
    "class=\"escape\"",
    "class=\"function\"",
    "class=\"function builtin\"",
    "class=\"function macro\"",
    "class=\"function method\"",
    "class=\"function special\"",
    "class=\"keyword\"",
    "class=\"label\"",
    "class=\"number\"",
    "class=\"operator\"",
    "class=\"property\"",
    "class=\"punctuation bracket\"",
    "class=\"punctuation delimiter\"",
    "class=\"punctuation special\"",
    "class=\"string\"",
    "class=\"string special\"",
    "class=\"string special key\"",
    "class=\"tag\"",
    "class=\"tag error\"",
    "class=\"type\"",
    "class=\"type builtin\"",
    "class=\"variable\"",
    "class=\"variable builtin\"",
    "class=\"variable parameter\"",
];

pub const CLASS_NAMES: &[&str] = &[
    "attribute",
    "boolean",
    "character special",
    "comment",
    "comment documentation",
    "constant",
    "constant builtin",
    "constant character",
    "constructor",
    "delimiter",
    "embedded",
    "escape",
    "function",
    "function builtin",
    "function macro",
    "function method",
    "function special",
    "keyword",
    "label",
    "number",
    "operator",
    "property",
    "punctuation bracket",
    "punctuation delimiter",
    "punctuation special",
    "string",
    "string special",
    "string special key",
    "tag",
    "tag error",
    "type",
    "type builtin",
    "variable",
    "variable builtin",
    "variable parameter",
];
